### PR TITLE
Cross-platform CMake integration

### PR DESCRIPTION
**Pull request by christiannicola**
Hey!

I've been following your devlogs, and yesterday you mentioned that you're interested in cross-platform development with clang. I'm not sure if you're interested in these changes, but they do setup the project in a way that is usable across all major PC platforms (windows, unix, darwin). 

I'm using CMake here since it works on all platforms. It manages all the project dependencies (pinned by version, statically compiled) and links them to the executable. Also included is a Github Actions workflow - the project is compiled in all available OS environments & compiler options available to ensure that everything is working correctly on your target platforms.

Msys2 support has been removed in this PR since I did not have a proper way of verifying that it works. It should, but I was not able to test it.

Let me know what you think about these changes - I'm happy to work on this a bit more if you have suggestions.

Cheers!

### CODE REVIEW

**Comment by britown88** [comment]
Hello!  This is neat! I do feel a little bad because the original thrust of this project was from hating CMAKE 😅 and wanting to give people on Windows a simple entry-point to C++ gamedev from Visual Studio with no further configuration.

If I were to merge this in it would be with the requirement that the original readme steps for building still work and don't require cmake, and I wouldn't want it to replace any of the work @krishean has done.

Another alternative is to link to the cmake fork inside the root readme!

I'm open to some discussion here, thanks for contributing!!

**Comment by christiannicola** [comment]
Sounds good if that's the direction we're heading here. I guess that this PR should not be merged then, since the project setup has been replaced with CMake entirely.

I did not know that CMake is a no-go.

We can still use the CI pipeline though; it does need a couple of changes to work with the Makefiles, but that's not too much of an issue.

Linking to my fork is fine, but that's up to you.

Either way - let me know how you want to proceed and I'll work on this a bit more tomorrow if needed!

**Comment by britown88** [comment]
No worries at all you had no way of knowing the original idea because this was something I threw together for a cohost commenter one morning 😅

Having the Github CI work for cross platform seems really useful, I've never personally used any of that so I don't know what all goes into it!

I'll link to the cmake fork in the readme!

**Comment by christiannicola** [comment]
CI on GitHub is pretty easy to setup. It's basically a single file that GitHub picks up automatically once it's present in your branch.

We could write a workflow that could:

- test all different configuration (OS/compiler)
- verify that the project builds correctly
- run against every PR that targets the main branch to safely integrate changes

If you're running the pipeline multiple times a day you could run into issues with the free tier, but it should suffice for a base project like this.

Let me know if it's something that's useful to you, and I'll create a PR for it tomorrow.

**Comment by krishean** [comment]
I have a workflow over [here](https://github.com/krishean/scratch/blob/devel/.github/workflows/build.yaml) that builds the makefiles on linux, macos, msys2, and cross compiles with gcc on linux for windows, and also builds the msvc project files as well if you want to take a look at it. Right now it only builds against my devel branch, but that can easily be changed. I can put in a pr if you would like to add it here.

**Pull request closed without merging**
